---
HelpSecurityIntro:
    Menu: Introduction
    MenuTip: Introduction to security systems
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/Introduction
    Text: |
        As you accept more work from Uplink Corporation you will encounter more and more security systems of different types and strengths. All security systems are designed with one primary goal - to keep you out, and as an agent you must learn to bypass them.
        
        Most systems can be simply disabled once Administrative access has been gained, but this method is considered unprofessional and is 'noisy' - most systems will detect this act and will begin tracing your connection immediately.
        
        In nearly all cases a better method exists - most systems can be bypassed or fooled in some way.

HelpSecurityProxy:
    Menu: The Proxy
    MenuTip: Information on the Proxy security system
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/The Proxy
    Text: |
        The primary purpose of the Proxy server is to stop unauthorised users from modifying records or logs. A system with a good Proxy server will permit you to examine records and logs but will not allow you to change them. As such, you will not be able to remove any logs of your actions, nor will you be able to make any alterations to any records on the target system.
        
        Proxy servers are extremely popular on government data systems (such as the social security database) and other systems where the data itself is sensitive. They can be bypassed simply by disabling them on the target computer (which will typically require admin access) or by running a Proxy_Disable tool. Both of these methods will cause you to get noticed. You can also bypass them silently with more advanced software tools and a Connection Analyser.

HelpSecurityFirewall:
    Menu: The Firewall
    MenuTip: Information on the Firewall security system
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/The Firewall
    Text: |
        The primary purpose of the Firewall is to prevent unauthorised usage of files on the target system. A good Firewall will stop you from copying, deleting or downloading any files located on the target computer.
        
        Firewalls are common on File Servers or any system where the contents of the files are sensitive or valuable. They can be bypassed simply by disabling them on the target computer (which will typically require admin access) or by running a Firewall_Disable tool. Both of these methods will cause you to get noticed. You can also bypass them silently with more advanced software tools and a Connection Analyser.

HelpSecurityMonitor:
    Menu: The Monitor
    MenuTip: Information on the Monitor security system
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/The Monitor
    Text: |
        Monitor systems are designed to detect unauthorised activity. They are usually triggered when a user attempts to hack a password, makes use of the Admin account, or starts deleting files. Once they have detected illegal activity they will sound the alarm and start an Active Trace on your connection. They will also flag your logs as suspicious.
        
        Monitor systems will also periodically check the other security systems running locally to see if they have been disabled.
        
        You can bypass a monitor system with a Connection Analyser HUD upgrade and a Monitor Bypass. This might allow you to hack without being noticed, if you tread carefully.

HelpSecurityVoice:
    Menu: Voice Print ID Systems
    MenuTip: Information on voice print security
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/Voice Print ID
    Text: |
        Many systems that require a specific person to log in use Voice Print technology. The user's voice is first sampled and analysed by the company, then digitised and encrypted onto their system. When that person logs in, (s)he reproduces a certain phrase or set of words. These are then analysed and compared.
        
        Recent advances in this area have made it very difficult to crack. For many years Digital Approximation software was capable of defeating these systems, but this is no longer the case. In most modern systems, the only real way is to obtain a sample of the users voice directly. Agents can then use Voice Analyser software to reproduce the phrase digitally from that sample.

HelpSecurityCypher:
    Menu: Elliptic Curve Systems
    MenuTip: Information on the Elliptic Curve system
    MainTitle: {{company_header}} Help
    Subtitle: Help/Security Systems/Elliptic Curve Security
    Text: |
        Faced with the growing threat of hackers, many companies have begun using Elliptic Curve Cryptography. A user on a system must input a large block of data in sequence, synchronised with the system. This cannot be done by hand - the timings must be perfect. Elliptic Curve Cryptography is popular due to the large amount of CPU power needed to force crack it.
        
        However, as with all cryptography, even this system can be broken given enough time and CPU cycles. Agents can use the Decypher software tool to force crack one of these systems, but a fast CPU rig will be required.
